In [1]:
pip install torch

  Using cached torch-2.7.1-cp312-none-macosx_11_0_arm64.whl.metadata (29 kB)
  Using cached sympy-1.14.0-py3-none-any.whl.metadata (12 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 68.6/68.6 MB 39.1 MB/s eta 0:00:0000:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.3/6.3 MB 46.5 MB/s eta 0:00:00
  Attempting uninstall: sympy
    Found existing installation: sympy 1.13.2
    Uninstalling sympy-1.13.2:
      Successfully uninstalled sympy-1.13.2
Note: you may need to restart the kernel to use updated packages.


In [2]:
import torch

my_list = [[1, 2, 3], [4, 5, 6]]
tensor = torch.tensor(my_list)

print(tensor)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [3]:
my_list = [[1, 2, 3], [4, 5, 6]]
tensor = torch.tensor(my_list)


print(tensor.shape)

torch.Size([2, 3])


In [4]:
print(tensor.dtype)

torch.int64


In [5]:
a = torch.tensor([[1, 1], [2, 2]])
b = torch.tensor([[2, 2], [3, 3]])

print(a + b)

tensor([[3, 3],
        [5, 5]])


In [6]:
a = torch.tensor([[1, 1], [2, 2]])
b = torch.tensor([[2, 2], [3, 3]])

print(a * b)

tensor([[2, 2],
        [6, 6]])


In [7]:
a = torch.tensor([[1, 1], [2, 2]])
b = torch.tensor([[2, 2], [3, 3]])

print(a @ b)

tensor([[ 5,  5],
        [10, 10]])


In [8]:
# Import PyTorch
import torch

temperatures = [[72, 75, 78], [70, 73, 76]]

# Create a tensor from temperatures
temp_tensor = torch.tensor(temperatures)

print(temp_tensor)

tensor([[72, 75, 78],
        [70, 73, 76]])


In [12]:
adjustment = torch.tensor([[2, 2, 2], [2, 2, 2]])

# Display the shape of the adjustment tensor
print("Adjustment shape:", adjustment.shape)

# Display the type of the adjustment tensor
print("Adjustment type:", adjustment.dtype)

print("Temperatures shape:", temp_tensor.shape)
print("Temperatures type:", temp_tensor.dtype)

Adjustment shape: torch.Size([2, 3])
Adjustment type: torch.int64
Temperatures shape: torch.Size([2, 3])
Temperatures type: torch.int64


In [13]:
adjustment = torch.tensor([[2, 2, 2], [2, 2, 2]])

# Add the temperatures and adjustment tensors
corrected_temperatures = temp_tensor + adjustment
print("Corrected temperatures:", corrected_temperatures)

Corrected temperatures: tensor([[74, 77, 80],
        [72, 75, 78]])


## Designing a Neural Network

In [14]:
# Importing as nn to avoid writing torch.nn
import torch.nn as nn

# Create input_tensor with three features
input_tensor = torch.tensor([[0.3471, 0.4547, -0.2356]])

# Define our linear layer
linear_layer = nn.Linear(in_features=3,out_features=2)

# Pass input through linear layer
output = linear_layer(input_tensor)
print(output) 

tensor([[-0.2191, -0.2062]], grad_fn=<AddmmBackward0>)


In [15]:
output = linear_layer(input_tensor)

In [18]:
print(linear_layer.weight)

print("\n",linear_layer.bias)

Parameter containing:
tensor([[-0.4884,  0.1531, -0.0526],
        [-0.1446,  0.1146, -0.1371]], requires_grad=True)

 Parameter containing:
tensor([-0.1316, -0.2404], requires_grad=True)


In [ ]:
# training

input_tensor = torch.tensor([[0.3471, 0.4547, -0.2356]])

# Create a Linear layer
linear_layer = nn.Linear(
                         in_features=3, 
                         out_features=2
                         )

# Pass input_tensor through the linear layer
output = linear_layer(input_tensor)

print(output)

## Hidden Layers and Parameters

In [20]:
# Stacking layers with nn.Sequential

# Create network with three linear layers
# model = nn.Sequential(nn.Linear(n_features, 8), # n_features represents number of input features    
#                       nn.Linear(8, 4),    
#                       nn.Linear(4, n_classes) # n_classes represents the number of output classes  
#                      )

In [21]:
# Create network with three linear layers
model = nn.Sequential(nn.Linear(10, 18),  # Takes 10 features and outputs 18  
                      nn.Linear(18, 20),  # Takes 18 and outputs 20
                      nn.Linear(20, 5)    # Takes 20 and outputs 5
                     )

In [22]:
# Parameters and model capacity

model = nn.Sequential(nn.Linear(8, 4),   
                      nn.Linear(4, 2)
                     )

### Manual parameter calculation

First layer has 4 neurons, each neuron has **8+1** parameters. 9 times 4 = **36 parameters**
Second layer has 2 neurons, each neuronhas **4+1** parameters. 5 times 2 = **10 parameters**

36 + 10 = **46 learnable parameters**

In [24]:
total = 0
for parameter in model.parameters():    
    total += parameter.numel()
print(total)

46


In [25]:
# training

input_tensor = torch.Tensor([[2, 3, 6, 7, 9, 3, 2, 1]])

# Create a container for stacking linear layers
model = nn.Sequential(nn.Linear(8, 4),
                nn.Linear(4, 1)
                )

output = model(input_tensor)
print(output)

tensor([[-1.0783]], grad_fn=<AddmmBackward0>)


In [26]:
# training part 2

model = nn.Sequential(nn.Linear(9, 4),
                      nn.Linear(4, 2),
                      nn.Linear(2, 1))

total = 0

# Calculate the number of parameters in the model
for p in model.parameters():
  total += p.numel()
  
print(f"The number of parameters in the model is {total}")

The number of parameters in the model is 53
